const DATA = [
  {
    id: 1,
    title: 'iPad Air 10.9 Wi-Fi 256GB New 2020 - Hàng Chính Hãng Apple',
    category: 'Apple',
    timer: 15,
    successAuction: 312,
    description: [
      'Thiết kế tinh tế, màu sắc thời thượng với độ mỏng 6.1mm',
      'Thiết kế của iPad Air 10.9 Wi-Fi New 2020 sẽ vuông vắn hơn so với những dòng iPad',
      'Màn hình có tần số quét 60Hz, tấm nền IPS LCD và kích thước 10.9 inch',
      'Chip A14 cho sức mạnh ấn tượng và bộ nhớ 128GB lưu trữ rộng rãi',
      'Hệ thống camera với cảm biến LiDAR hỗ trợ quay phim chất lượng 4K siêu nét',
    ],
    rate: 3.5,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceDefault: 148000,
    images: [
      '/images/products/1.png',
      '/images/products/2.jpeg',
      '/images/products/3.jpeg',
      '/images/products/4.jpeg',
      '/images/products/5.jpeg',
    ],
  },
  {
    id: 2,
    title: 'Điện Thoại iPhone 12 Pro Max 128GB - Hàng Chính Hãng',
    category: 'iPhone 12',
    timer: 15,
    successAuction: 147,
    description: [
      'Màn hình Super Retina XDR 6.7 inch2',
      'Ceramic Shield, chất liệu kính bền chắc nhất từng có trên điện thoại thông minh',
      'Mạng 5G cho tốc độ tải xuống siêu nhanh, xem video và nghe nhạc trực tuyến chất lượng cao',
      'A14 Bionic, chip nhanh nhất từng có trên điện thoại thông minh',
      'Hệ thống camera chuyên nghiệp 12MP với camera Ultra Wide, Wide và Telephoto; phạm vi thu phóng quang học 5x; chế độ Ban Đêm, Deep Fusion, HDR thông minh thế hệ 3, Apple ProRAW, và khả năng quay video HDR Dolby Vision 4K',
      'LiDAR Scanner cải thiện trải nghiệm thực tế ảo tăng cường và chụp ảnh chân dung ở chế độ Ban Đêm',
      'iOS 14 với các tiện ích được thiết kế lại trên Màn Hình Chính, Thư Viện Ứng Dụng hoàn toàn mới, App Clips cùng nhiều tính năng khác',
    ],
    rate: 4,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceDefault: 22000000,
    images: [
      '/images/products/6.jpeg',
      '/images/products/7.jpeg',
      '/images/products/8.jpeg',
      '/images/products/9.jpeg',
      '/images/products/10.jpeg',
    ],
  },

  {
    id: 3,
    title:
      'Tai Nghe Bluetooth Apple AirPods Pro True Wireless - MWP22 - Hàng Chính Hãng VN/A',
    category: 'AirPods',
    timer: 15,
    successAuction: 2270,
    description: [
      'Tính năng Chủ Động Khử Tiếng Ồn tạo ra âm thanh sống động',
      'Chế Độ Xuyên Âm giúp bạn nghe và tương tác với thế giới xung quanh',
      'Chế Độ Xuyên Âm giúp bạn nghe và tương tác với thế giới xung quanh',
      'EQ thích ứng sẽ tự động điều chỉnh nhạc theo kích thước tai của bạn',
      'Thiết lập dễ dàng cùng tính năng nhận biết khi đeo cho trải nghiệm tuyệt vời (2)',
    ],
    rate: 2.5,
    options: ['Màu trắng', 'Màu đen', 'Màu hồng'],
    priceDefault: 49500000,
    images: [
      '/images/products/11.jpeg',
      '/images/products/12.jpeg',
      '/images/products/13.jpeg',
      '/images/products/14.jpeg',
      '/images/products/15.jpeg',
    ],
  },

  {
    id: 4,
    title:
      'Apple iMac 21.5 2017 MHK03SA/A (Core i5 2.3GHz/ 8GB/ 256GB SSD/ FHD) - Hàng Chính Hãng',
    category: 'iMac',
    timer: 15,
    successAuction: 678,
    description: [
      'Bộ vi xử lý Intel Core i5 mạnh mẽ',
      'Màn hình Full HD sắc nét, màu sắc chính xác',
      'Tốc độ nhanh hơn với ổ cứng SSD',
      'Đầy đủ loạt kết nối hàng đầu',
    ],
    rate: 2.5,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceDefault: 26000000,
    images: [
      '/images/products/16.jpeg',
      '/images/products/17.jpeg',
      '/images/products/18.jpeg',
      '/images/products/19.jpeg',
      '/images/products/20.png',
    ],
  },

  {
    id: 5,
    title:
      'Apple Macbook Pro 2020 M1 - 13 Inchs (Apple M1/ 8GB/ 256GB) - Hàng Chính Hãng',
    category: 'Macbook',
    timer: 15,
    successAuction: 1245,
    description: [
      'Chip M1 do Apple thiết kế tạo ra một cú nhảy vọt về hiệu năng máy học, CPU và GPU',
      'Làm được nhiều việc hơn với thời lượng pin lên đến 20 giờ, thời lượng pin lâu nhất trong các dòng máy tính Mac từ trước đến nay',
      'CPU 8 lõi cho hiệu năng nhanh hơn đến 2.8x, xử lý các luồng công việc nhanh hơn bao giờ hết',
      'GPU 8 lõi với tốc độ xử lý đồ họa nhanh gấp 5x cho các ứng dụng và game có đồ họa khủng',
      'Ổ lưu trữ SSD siêu nhanh khởi chạy ứng dụng và mở tập tin chỉ trong tích tắc',
      'Màn hình Retina với độ sáng 500 nit cho màu sắc sống động và chi tiết ấn tượng',
    ],
    rate: 3.5,
    options: ['128GB', '256GB', '512GB'],
    priceDefault: 31490000,
    images: [
      '/images/products/21.jpeg',
      '/images/products/22.jpeg',
      '/images/products/23.jpeg',
      '/images/products/24.jpeg',
      '/images/products/25.jpeg',
    ],
  },
  {
    id: 6,
    title:
      'Apple Mac Mini 2020 M1 (Apple M1/ 16GB/ 256GB) - Z12N000B8 - Hàng Chính Hãng',
    category: 'Mac mini',
    timer: 15,
    successAuction: 189,
    description: [
      'Bước nhảy vọt về hiệu năng',
      'CPU 8 nhân, xử lý mọi việc trong chớp mắt',
      'Sức mạnh đồ họa nhanh hơn tới 6 lần',
      'Giải phóng sức mạnh với 16 nhân Neural Engine',
      'Thiết kế nhỏ gọn',
      'Ổ cứng SSD siêu tốc',
      'Mở rộng kết nối',
    ],
    rate: 1.5,
    options: ['128GB', '256GB', '512GB'],
    priceDefault: 23499000,
    images: [
      '/images/products/26.jpeg',
      '/images/products/27.jpeg',
      '/images/products/28.png',
      '/images/products/29.jpeg',
      '/images/products/30.jpeg',
    ],
  },
  {
    id: 7,
    title:
      'Apple Mac Mini 2020 M1 (Apple M1/ 16GB/ 256GB) - Z12N000B8 - Hàng Chính Hãng',
    category: 'Mac mini',
    timer: 15,
    successAuction: 189,
    description: [
      'Bước nhảy vọt về hiệu năng',
      'CPU 8 nhân, xử lý mọi việc trong chớp mắt',
      'Sức mạnh đồ họa nhanh hơn tới 6 lần',
      'Giải phóng sức mạnh với 16 nhân Neural Engine',
      'Thiết kế nhỏ gọn',
      'Ổ cứng SSD siêu tốc',
      'Mở rộng kết nối',
    ],
    rate: 1.5,
    options: ['128GB', '256GB', '512GB'],
    priceDefault: 23499000,
    images: [
      '/images/products/26.jpeg',
      '/images/products/27.jpeg',
      '/images/products/28.jpeg',
      '/images/products/29.jpeg',
      '/images/products/30.jpeg',
    ],
  },
  {
    id: 8,
    title:
      'Apple Macbook Pro 2020 M1 - 13 Inchs (Apple M1/ 8GB/ 256GB) - Hàng Chính Hãng',
    category: 'Macbook',
    timer: 15,
    successAuction: 1245,
    description: [
      'Chip M1 do Apple thiết kế tạo ra một cú nhảy vọt về hiệu năng máy học, CPU và GPU',
      'Làm được nhiều việc hơn với thời lượng pin lên đến 20 giờ, thời lượng pin lâu nhất trong các dòng máy tính Mac từ trước đến nay',
      'CPU 8 lõi cho hiệu năng nhanh hơn đến 2.8x, xử lý các luồng công việc nhanh hơn bao giờ hết',
      'GPU 8 lõi với tốc độ xử lý đồ họa nhanh gấp 5x cho các ứng dụng và game có đồ họa khủng',
      'Ổ lưu trữ SSD siêu nhanh khởi chạy ứng dụng và mở tập tin chỉ trong tích tắc',
      'Màn hình Retina với độ sáng 500 nit cho màu sắc sống động và chi tiết ấn tượng',
    ],
    rate: 3.5,
    options: ['128GB', '256GB', '512GB'],
    priceDefault: 31490000,
    images: [
      '/images/products/21.jpeg',
      '/images/products/22.jpeg',
      '/images/products/23.jpeg',
      '/images/products/24.jpeg',
      '/images/products/25.jpeg',
    ],
  },

  {
    id: 9,
    title: 'iPad Air 10.9 Wi-Fi 256GB New 2020 - Hàng Chính Hãng Apple',
    category: 'Apple',
    timer: 15,
    successAuction: 312,
    description: [
      'Thiết kế tinh tế, màu sắc thời thượng với độ mỏng 6.1mm',
      'Thiết kế của iPad Air 10.9 Wi-Fi New 2020 sẽ vuông vắn hơn so với những dòng iPad',
      'Màn hình có tần số quét 60Hz, tấm nền IPS LCD và kích thước 10.9 inch',
      'Chip A14 cho sức mạnh ấn tượng và bộ nhớ 128GB lưu trữ rộng rãi',
      'Hệ thống camera với cảm biến LiDAR hỗ trợ quay phim chất lượng 4K siêu nét',
    ],
    rate: 3.5,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceDefault: 148000,
    images: [
      '/images/products/1.png',
      '/images/products/2.jpeg',
      '/images/products/3.jpeg',
      '/images/products/4.jpeg',
      '/images/products/5.jpeg',
    ],
  },

  {
    id: 10,
    title:
      'Tai Nghe Bluetooth Apple AirPods Pro True Wireless - MWP22 - Hàng Chính Hãng VN/A',
    category: 'AirPods',
    timer: 15,
    successAuction: 2270,
    description: [
      'Tính năng Chủ Động Khử Tiếng Ồn tạo ra âm thanh sống động',
      'Chế Độ Xuyên Âm giúp bạn nghe và tương tác với thế giới xung quanh',
      'Chế Độ Xuyên Âm giúp bạn nghe và tương tác với thế giới xung quanh',
      'EQ thích ứng sẽ tự động điều chỉnh nhạc theo kích thước tai của bạn',
      'Thiết lập dễ dàng cùng tính năng nhận biết khi đeo cho trải nghiệm tuyệt vời (2)',
    ],
    rate: 2.5,
    options: ['Màu trắng', 'Màu đen', 'Màu hồng'],
    priceDefault: 49500000,
    images: [
      '/images/products/11.jpeg',
      '/images/products/12.jpeg',
      '/images/products/13.jpeg',
      '/images/products/14.jpeg',
      '/images/products/15.jpeg',
    ],
  },
  {
    id: 11,
    title: 'Điện Thoại iPhone 12 Pro Max 128GB - Hàng Chính Hãng',
    category: 'iPhone 12',
    timer: 15,
    successAuction: 147,
    description: [
      'Màn hình Super Retina XDR 6.7 inch2',
      'Ceramic Shield, chất liệu kính bền chắc nhất từng có trên điện thoại thông minh',
      'Mạng 5G cho tốc độ tải xuống siêu nhanh, xem video và nghe nhạc trực tuyến chất lượng cao',
      'A14 Bionic, chip nhanh nhất từng có trên điện thoại thông minh',
      'Hệ thống camera chuyên nghiệp 12MP với camera Ultra Wide, Wide và Telephoto; phạm vi thu phóng quang học 5x; chế độ Ban Đêm, Deep Fusion, HDR thông minh thế hệ 3, Apple ProRAW, và khả năng quay video HDR Dolby Vision 4K',
      'LiDAR Scanner cải thiện trải nghiệm thực tế ảo tăng cường và chụp ảnh chân dung ở chế độ Ban Đêm',
      'iOS 14 với các tiện ích được thiết kế lại trên Màn Hình Chính, Thư Viện Ứng Dụng hoàn toàn mới, App Clips cùng nhiều tính năng khác',
    ],
    rate: 4,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceDefault: 22000000,
    images: [
      '/images/products/6.jpeg',
      '/images/products/7.jpeg',
      '/images/products/8.jpeg',
      '/images/products/9.jpeg',
      '/images/products/10.jpeg',
    ],
  },
  {
    id: 12,
    title:
      'Apple iMac 21.5 2017 MHK03SA/A (Core i5 2.3GHz/ 8GB/ 256GB SSD/ FHD) - Hàng Chính Hãng',
    category: 'iMac',
    timer: 15,
    successAuction: 678,
    description: [
      'Bộ vi xử lý Intel Core i5 mạnh mẽ',
      'Bộ vi xử lý Intel Core i5 mạnh mẽ',
      'Bộ vi xử lý Intel Core i5 mạnh mẽ',
      'Màn hình Full HD sắc nét, màu sắc chính xác',
      'Tốc độ nhanh hơn với ổ cứng SSD',
      'Đầy đủ loạt kết nối hàng đầu',
    ],
    rate: 2.5,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceDefault: 26000000,
    images: [
      '/images/products/16.jpeg',
      '/images/products/17.jpeg',
      '/images/products/18.png',
      '/images/products/19.jpeg',
      '/images/products/20.png',
    ],
  },
];

export default DATA;
